solr:
  image: solr:6.6
  ports:
    - '8983:8983'

web:
  build: .
  links:
    - solr
  ports:
    - '443:443'
  env_file:
    - .production.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - solr
  env_file:
    - .production.env