version: '3'

services:
  solr:
    image: solr:6.6
    ports:
      - '8983:8983'

  web:
    build: .
    links:
      - solr
    ports:
      - '443:443'
    volumes:
      - ./config/docker/nginx:/coursedy/nginx_conf
    env_file:
      - .production.env
    entrypoint: /web_entrypoint.sh

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - solr
    env_file:
      - .production.env
    entrypoint: /sidekiq_entrypoint.sh