default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  host: <%= ENV['CD_DATABASE_HOST'] %>
  database: <%= ENV['CD_DATABASE_NAME'] %>
  username: <%= ENV['CD_DATABASE_USER'] %>
  password: <%= ENV['CD_DATABASE_PASSWORD'] %>